
const DEBUGGER_PREFIX = "blockflow"
const DEBUGGER_REGISTER_PROCESSOR = DEBUGGER_PREFIX + ":register_processor"
const DEBUGGER_UNREGISTER_PROCESSOR = DEBUGGER_PREFIX + ":unregister_processor"
const DEBUGGER_BREAKPOINT = DEBUGGER_PREFIX + ":breakpoint"
const DEBUGGER_PROCESSOR_PROCESSING_COLLECTION = DEBUGGER_PREFIX + ":process_collection"
const DEBUGGER_PROCESSOR_PROCESSING_COMMAND = DEBUGGER_PREFIX + ":process_command"
